### ISSUE TITLE
get_total_results public function error

### ISSUE THREAD

**Issue by ronnyrtg** [n1crack/IgnitedDatatables-php-library#5]
I have just downloaded IgnitedDatatables for native php and tested one of the examples (basic_init). It was not working and firebug showed this error.
"Notice: Undefined property: Datatables::$like in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\BDNC\OBS\IgnitedDatatables\Datatables.php on line 408"
When I commented lines 408 and 409 it was able to display the Datatable.

**Comment by n1crack** [comment]
https://github.com/n1crack/Datatables new library is out.
